### ISSUE TITLE
Create the LLM Currency trait

### ISSUE THREAD

**Issue by flipchan** [liberland/liberland_substrate#58]
For easy to use 

similar to:
```rust
type Currency: ReservableCurrency<Self::AccountId>
			+ LockableCurrency<Self::AccountId, Moment = Self::BlockNumber>;
```

**Comment by michalptacnik** [comment]
Can I get a better explanation as to what this issue is about?

**Comment by kacperzuk-neti** [comment]
@michalptacnik 
When configuring pallets like democracy or elections, one of the configuration options is "Currency". Currently we use pallet_balances (a.k.a. LLD) as a Currency for everything. We've modified democracy and elections pallet, so that they use custom LLM interfaces directly, ignoring the configured Currency.

This issue is about making LLM compatible with Currency trait - in effect making it possible to use it for stuff with just configuration instead of modifying pallets. It might have to be quite creative to handle citizenship, but that's something we could abuse locks for (if you're not a citizen, all your funds are reported as "locked" for democracy etc).

So the end result would be reducing the amount of modification we do to upstream pallets, making maintenance easier, reliability higher and audits cheaper. Probably it would also fix issues like polkadot UI showing "LLD" instead of "LLM" in some places.

**Comment by kacperzuk-neti** [comment]
WONTFIX, we now have other modifications to upstream pallets that can't be worked around with currency trait anyway.
