### ISSUE TITLE
Voting Power Economy

### ISSUE THREAD

**Issue by michalptacnik** [liberland/liberland_substrate#63]
Hello!

Current solution for referendums is that we have llmpolitics and llmpoliticslock which means that if there are two referendums and you have 1000 LLM, you need to decide how much to vote for which referendum
This is actually against requirements and needs to be changed. Might I ask for you to look into it?

Explanation: You should always be able to vote yes or no on referendums with the full LLM you have even if there are many referendums running in paralel.  is this doable? Given that the interaction with LLM is custom, we should just remove LLMpoliticsLock and it should work? It would also fix some of the bugs we currently have.

Note:
Polkadot doesn't seem to have this issue because their timing of referenda is synchronized, meaning, they have functionally (mostly) one referendum per referendum period. This isn't the case in LSC (us) and it is a good thing - we want more referenda. But we have to resolve the issue above.

**Comment by flipchan** [comment]
Current solution for referendums is that we have llmpolitics and llmpoliticslock which means that if there are two referendums and you have 1000 LLM, you need to decide how much to vote for which referendum:

This is wrong. As llmpolitics and llmpoliticslock are two different states of the on-chain asset llm. When you vote you lock in your tokens for the yes or no vote. When you do that you lock your tokens in a lock period. This is by design and can be researched more by looking into to on-chain voting for substrate based chains. This is a misconseption and the entire balance of your llm can not be used multiple times to vote with that is impossible.

**Comment by flipchan** [comment]
```Polkadot doesn't seem to have this issue because their timing of referenda is synchronized, meaning, they have functionally (mostly) one referendum per referendum period. This isn't the case in LSC (us) and it is a good thing - we want more referenda. But we have to resolve the issue above.```

Polkadot has the same voting logic

**Comment by flipchan** [comment]
This is standard voting logic and shall not be changed without breaking more things

**Comment by michalptacnik** [comment]
We can't just dismiss this, it is a requirement. What Dorian suggested was removing or tweaking the locking, so that you only lock within the one given referendum.
The process works like this:
1. You vote with X LLM
2. You decide to vote again with X+Y LLM
3. You can, the first vote is negated, the second vote is supperceded.
Meaning that the locking is only necessary for weighted voting, i.e. when you lock your LLM for longer than the voting period. 

Do we have some arguments as to why the above doesn't apply or why this seems much more difficult than this logic would suggest?

**Comment by kacperzuk-neti** [comment]
Fixed.
